services:
  main:
    build:
      context: ..
      dockerfile: ./.devcontainer/dev.Dockerfile
      args:
        - USER_NAME=${CONTAINER_USERNAME}
        - USE_CN_MIRROR=${USE_CN_MIRROR}
    ports:
      - "6080" # noVNC web interface
      - "5901" # VNC direct connection
      - "5555" # ADB
      - "4723" # Appium
      - "22" # ssh
    environment:
      - VNC_PASSWD=${VNC_PASSWD}
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
      - com.storyteller_f.sign_path=${COM_STORYTELLER_F_SIGN_PATH}
      - com.storyteller_f.sign_key=${COM_STORYTELLER_F_SIGN_KEY}
      - com.storyteller_f.sign_alias=${COM_STORYTELLER_F_SIGN_ALIAS}
      - com.storyteller_f.sign_store_password=${COM_STORYTELLER_F_SIGN_STORE_PASSWORD}
      - com.storyteller_f.sign_key_password=${COM_STORYTELLER_F_SIGN_KEY_PASSWORD}
    volumes:
      - ..:/workspace/mini-macro-memo:cached
      - ./logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - ./data/authorized_keys:${CONTAINER_HOME}/.ssh/authorized_keys
      - avd_data:${CONTAINER_HOME}/.android/avd
      - sdk_data:${CONTAINER_HOME}/Android/Sdk
      - bash_history:${CONTAINER_HOME}/.desktop-in-docker/.bash_history
      - gradle_data:${CONTAINER_HOME}/.gradle
      - konan_data:${CONTAINER_HOME}/.konan
      - m2_data:${CONTAINER_HOME}/.m2
      - chrome_cache:${CONTAINER_HOME}/.cache/google-chrome
      - chrome_config:${CONTAINER_HOME}/.config/google-chrome
      - google_cache:${CONTAINER_HOME}/.cache/Google
      - google_config:${CONTAINER_HOME}/.config/Google
      - google_local:${CONTAINER_HOME}/.local/share/Google
      - vscode_data:${CONTAINER_HOME}/.vscode
      - code_config:${CONTAINER_HOME}/.config/Code
    shm_size: '2gb' # Allocate more shared memory
    devices:
      - /dev/kvm
    security_opt:
      - seccomp:unconfined

volumes:
  avd_data:
  sdk_data:
    name: sdk_data
    external: true
  bash_history:
  gradle_data:
  konan_data:
  m2_data:
  chrome_cache:
  chrome_config:
  google_cache:
  google_config:
  google_local:
  vscode_data:
  code_config:
